#!/bin/bash

# utility aliases
alias ls='ls -l -G'
alias find_svn='find . \( -name .svn -o -name "*~" \) -prune -o';
alias grepc='grep --color=auto -HnT'
alias grep_svn='grepc --exclude-dir=.svn --exclude=*~'
alias tree='tree -C'
alias vim='mvim -v'
alias regex='perl -pi -w -e'
alias svn_rm="svn st | awk '/!/ {print \"svn rm \"$2}' | bash" # removes previously deleted files from repo
alias diffdir="diff -iEbBqr -x '*~' -x .svn -x *.pyc --strip-trailing-cr"

alias vless='vim -u /usr/share/vim/vim72/macros/less.vim'

fjson () { php /Users/andrew/Documents/library/php/formatJson.php $@; }
fcurl () { export i=`curl $@`; fjson \'$i\'; }

alias start_nginx='sudo launchctl load /Library/LaunchDaemons/dev.nginx.plist'
alias stop_nginx='sudo launchctl unload /Library/LaunchDaemons/dev.nginx.plist'
alias restart_nginx='stop_nginx ; sleep 1 ; start_nginx'
